org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.250
loader_version_range=[1,)

mod_version = 2.0.0
mod_group_id = com.dolthhaven
mod_id=doltastic_enchantments
mod_name=Doltastic Enchantments
mod_license=MIT
mod_authors=DoltHHaven
mod_description=Add

alfinolib=T3iUMjhn
blueprint=8.1.0
emi=5sIPA1To
jei=19.27.0.335
ie=1axWAPS7
rr=reliable-remover:gTZ62Sja