modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/thelegitdolt/dolt-mod-how/issues"
license = "https://github.com/thelegitdolt/dolt-mod-how/issues"

[[mods]]
modId = "doltastic_enchantments"
version = "${file.jarVersion}"
authors = "Dolt"
credits = "Dolt H. Haven"
displayName = "Doltastic Enchantments"
description = '''
        Hello
    '''

[[dependencies.doltastic_enchantments]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[7.1.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.doltastic_enchantments]]
    modId = "immersiveenchanting"
    mandatory = true
    versionRange = "[4.0.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.doltastic_enchantments]]
    modId = "emi"
    mandatory = false
    versionRange = "[1.1.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.doltastic_enchantments]]
    modId = "reliable_remover"
    mandatory = false
    versionRange = "[2.0.0,)"
    ordering = "AFTER"
    side = "BOTH"
