modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/thelegitdolt/doltastic_enchantments/issues"
license = "https://github.com/thelegitdolt/doltastic_enchantments/license"

[[mods]]
modId = "doltastic_enchantments"
version = "${file.jarVersion}"
authors = "Dolt"
credits = "Dolt H. Haven"
displayName = "Doltastic Enchantments"
description = '''
    Addon for Immersive Enchanting mod which does things to my vision
'''

[[dependencies.doltastic_enchantments]]
    modId = "blueprint"
    type = "required"
    versionRange = "[7.1.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.doltastic_enchantments]]
    modId = "immersiveenchanting"
    type = "required"
    versionRange = "[5.0.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.doltastic_enchantments]]
    modId = "emi"
    type = "optional"
    versionRange = "[1.1.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.doltastic_enchantments]]
    modId = "reliable_remover"
    type = "optional"
    versionRange = "[2.0.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[mixins]]
    config="doltastic_enchantments.mixins.json"

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

